# Generated by Django 5.0.6 on 2024-06-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="image", field=models.CharField(max_length=200),
        ),
    ]
