# Generated by Django 5.0.6 on 2024-06-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="other_tech",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="subtopic",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
