# Generated by Django 5.0.6 on 2024-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_image_alter_project_other_tech_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tech",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
